version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: Restaurant.API/Dockerfile
    depends_on: 
    - sqldata

  sqldata: 
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
    - SA_PASSWORD=Naosei.2023
    - ACCEPT_EULA=Y 
    volumes:
    - C:\dev\Dados\Volumes\mssql:/var/opt/mssql/data
    ports:
    - "1450:1433"
